# Generated by Django 4.2.7 on 2023-11-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_orders_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='paymentstatus',
            new_name='razorpay_status',
        ),
    ]
